Add test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,7 +20,16 @@ jobs:
       - run:
           name: Load test data into Solr
           command: |
-            set -x
             # Wait for Solr core to load
             sleep 60
             docker exec -it --user=solr solr_container bin/post -c mycore example/exampledocs/manufacturers.xml
+      - run:
+          name: Test Solr
+          command: |
+            sleep 10
+            data=$(docker exec -it --user=solr solr_container wget -q -0 - 'http://localhost:8983/solr/gettingstarted/select?q=id%3Adell')
+            if ! egrep -q 'One Dell Way Round Rock, Texas 78682' <<<$data; then
+              echo "An error occurred; data did not load"
+              exit 1
+            fi
+
